CREATE TABLE IF NOT EXISTS Players (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	name VARCHAR(255) NOT NULL,
	level SMALLINT NOT NULL DEFAULT 1,
	exp INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS Levels (
	level SMALLINT NOT NULL AUTO_INCREMENT UNIQUE,
	lvlup_exp INTEGER NOT NULL,
	assigned_event INTEGER COMMENT 'For example getting level 100',
	PRIMARY KEY(level)
);


CREATE TABLE IF NOT EXISTS Events (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	name VARCHAR(255) NOT NULL,
	exp_gained INTEGER NOT NULL DEFAULT 0,
	special BOOLEAN NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS PlayerEvents (
	player INTEGER NOT NULL,
	event INTEGER NOT NULL,
	updated_at DATETIME NOT NULL,
	repeats INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(player, event)
);


ALTER TABLE Players
ADD FOREIGN KEY(level) REFERENCES Levels(level)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PlayerEvents
ADD FOREIGN KEY(event) REFERENCES Events(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE PlayerEvents
ADD FOREIGN KEY(player) REFERENCES Players(id)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE Levels
ADD FOREIGN KEY(assigned_event) REFERENCES Events(id)
ON UPDATE CASCADE ON DELETE SET NULL;